# Funding options for Staticwall
# "Sets wallpapers until it... doesn't" (and your support helps keep it that way)

# GitHub Sponsors
# github: 1ay1

# Ko-fi (for coffee-based donations)
# ko_fi: 1ay1

# Patreon (for recurring support)
# patreon: 1ay1

# Open Collective (for transparent funding)
# open_collective: staticwall

# Custom links (you can add your own)
# custom: ['https://paypal.me/1ay1', 'https://buymeacoffee.com/1ay1']

# Uncomment the platforms you want to use above
# For now, this file exists to show we're thinking about sustainability
